### ISSUE TITLE
Server and client crash

### ISSUE THREAD

**Issue by Lice2** [Resynth-Minecraft-Mod/Resynth-Mod#20]
Hi . Unfortunately, I found another mistake.
I accidentally mined a blaze rod plant with a sword. Then the server and the client crashed.

 

Time: 06.10.19 16:17
Description: Exception in server tick loop

java.lang.NoSuchMethodError: com.ki11erwolf.resynth.plant.block.BlockBiochemicalPlant.playPopSound(Lnet/minecraft/world/World;Lnet/minecraft/entity/player/PlayerEntity;)V
at com.ki11erwolf.resynth.plant.block.BlockBiochemicalPlant.func_220051_a(BlockBiochemicalPlant.java:135) ~[?:3.1.0] {re:classloading,pl:runtimedistcleaner:A}
at net.minecraft.block.BlockState.func_215687_a(BlockState.java:274) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:322) ~[?:?] {re:classloading}
at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:847) ~[?:?] {re:classloading,pl:accesstransformer:B}
at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:36) ~[?:?] {re:classloading}
at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:10) ~[?:?] {re:classloading}
at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:classloading,pl:accesstransformer:B}
at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:classloading}
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:classloading,pl:accesstransformer:B}
at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:699) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:693) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?] {re:classloading,pl:accesstransformer:B}
at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:678) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:626) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at java.lang.Thread.run(Unknown Source) [?:1.8.0_211] {}

**Comment by LMelaia** [comment]
This will be fixed in the next release :). Thanks for letting me know!
